#!/bin/sh
# One-time setup (safe to re-run) of Watchgrid with Docker: uses an
# existing PostgreSQL container, or bundles one (postgres:16-alpine) if
# none is running. Run as root from the unpacked bundle folder:
#   sudo sh setup.sh
# Needs a file `db-password` (the password to give the watchgrid DB user);
# it is moved into watchgrid.env and never printed.
set -eu
cd "$(dirname "$0")"
D=$(command -v docker 2>/dev/null || echo /usr/local/bin/docker)
[ "$(id -u)" -eq 0 ] || { echo "run as root: sudo sh $0" >&2; exit 1; }
OWNER_UID=$(stat -c %u .)
OWNER_GID=$(stat -c %g .)

if [ -f db-password ]; then
    PW=$(cat db-password)
elif [ -f watchgrid.env ]; then
    PW=$(sed -n 's#^DATABASE_URL=postgres://watchgrid:\([^@]*\)@.*#\1#p' watchgrid.env)
else
    echo "missing db-password" >&2; exit 1
fi

# 1. Which PostgreSQL: an existing container (PG_CONTAINER or the first
#    running postgres image), else a bundled one in this stack.
PG=${PG_CONTAINER:-$($D ps --format '{{.Names}} {{.Image}}' | awk 'tolower($2) ~ /postgres|postgis|timescale/ {print $1; exit}')}
if [ -z "$PG" ]; then
    STOPPED=$($D ps -a --format '{{.Names}} {{.Image}}' | awk 'tolower($2) ~ /postgres|postgis|timescale/ {print $1}')
    [ -z "$STOPPED" ] || echo "note: stopped PostgreSQL container(s) found: $STOPPED (start one and re-run to use it instead)"
    echo "PostgreSQL: bundled (postgres:16-alpine, data in $(pwd)/db)"
    BUNDLED=1
    # Host networking: Watchgrid sees clients' real addresses (sessions,
    # sign-in throttling) and reaches cameras directly. The database only
    # listens on the NAS's loopback.
    DB_HOST=127.0.0.1
    DB_PORT=${WATCHGRID_DB_PORT:-5433}
    NETWORK="    network_mode: host
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: watchgrid-db
    restart: unless-stopped
    env_file: db.env
    ports:
      - \"127.0.0.1:$DB_PORT:5432\"
    volumes:
      - ./db:/var/lib/postgresql/data
    stop_grace_period: 30s
    healthcheck:
      test: [\"CMD-SHELL\", \"pg_isready -U watchgrid -d watchgrid\"]
      interval: 5s
      timeout: 5s
      retries: 20"
else
    BUNDLED=0
    echo "PostgreSQL container: $PG"
    # 2. Role and database (idempotent). The password travels as an env var.
    WG_PW="$PW" $D exec -i -e WG_PW "$PG" sh -c 'psql -q -v ON_ERROR_STOP=1 -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-${POSTGRES_USER:-postgres}}" -v pw="$WG_PW"' <<'SQL'
SELECT 'CREATE ROLE watchgrid LOGIN' WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'watchgrid') \gexec
ALTER ROLE watchgrid WITH LOGIN PASSWORD :'pw';
SELECT 'CREATE DATABASE watchgrid OWNER watchgrid' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'watchgrid') \gexec
SQL
    echo "database 'watchgrid' ready"

    # 3. How Watchgrid reaches it: a published port → host networking;
    #    otherwise join the database container's network.
    PUBLISHED=$($D port "$PG" 5432/tcp 2>/dev/null | head -1 || true)
    if [ -n "$PUBLISHED" ]; then
        DB_HOST=127.0.0.1
        DB_PORT=${PUBLISHED##*:}
        NETWORK="    network_mode: host"
    else
        NET=$($D inspect -f '{{range $k, $v := .NetworkSettings.Networks}}{{$k}} {{end}}' "$PG" | awk '{print $1}')
        if [ "$NET" = bridge ]; then
            echo "PostgreSQL has no published port and is on the default network; publish 5432 or use a named network." >&2
            exit 1
        fi
        DB_HOST=$PG
        DB_PORT=5432
        NETWORK="    ports:
      - \"8090:8090\"
    networks: [db]
networks:
  db:
    name: $NET
    external: true"
    fi
fi
echo "database address: $DB_HOST:$DB_PORT"

# 4. Configuration.
umask 077
if [ "$BUNDLED" = 1 ]; then
    printf 'POSTGRES_USER=watchgrid\nPOSTGRES_DB=watchgrid\nPOSTGRES_PASSWORD=%s\n' "$PW" > db.env
    mkdir -p db
fi
{
    echo "DATABASE_URL=postgres://watchgrid:$PW@$DB_HOST:$DB_PORT/watchgrid"
    grep -v '^DATABASE_URL=' watchgrid.env 2>/dev/null || grep -v '^DATABASE_URL=' watchgrid.env.example
} > watchgrid.env.new
mv watchgrid.env.new watchgrid.env
rm -f db-password
umask 022

cat > compose.nas.yml <<YAML
# Generated by setup.sh.
services:
  watchgrid:
    build: .
    image: watchgrid:latest
    container_name: watchgrid
    restart: unless-stopped
    env_file: watchgrid.env
    user: "$OWNER_UID:$OWNER_GID"
    volumes:
      - ./config:/etc/watchgrid
      - ./state:/var/lib/watchgrid
      - \${RECORDINGS:-./recordings}:/recordings
    stop_grace_period: 45s
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
$NETWORK
YAML
[ -f .env ] || printf 'COMPOSE_FILE=compose.nas.yml\n' > .env
grep -q '^COMPOSE_FILE=' .env || printf 'COMPOSE_FILE=compose.nas.yml\n' >> .env
mkdir -p config state recordings
chown "$OWNER_UID:$OWNER_GID" config state recordings

# 5. Build and start.
$D compose up -d --build
printf 'waiting for Watchgrid'
i=0
until curl -sf http://127.0.0.1:8090/api/v1/health >/dev/null 2>&1; do
    i=$((i + 1))
    if [ "$i" -gt 30 ]; then
        echo; echo "Watchgrid did not answer. Logs:"; $D compose logs --tail 20 watchgrid; exit 1
    fi
    printf '.'; sleep 1
done
echo " up."
echo
echo "Create the first account:  sudo $D exec -it watchgrid watchgrid user create <username>"
echo "Then open http://$(ip -4 route get 1.1.1.1 | sed -n 's/.* src \([0-9.]*\).*/\1/p'):8090"
